name: trinity_wizard_test
description: "A Trinity Wizard project test"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  analyzer: ^6.4.1                               # A versatile package for efficient code analysis in Flutter projects.
  auto_route: ^8.2.0                             # A Flutter routing library that generates route code.
  cupertino_icons: ^1.0.6
  connectivity_plus: ^6.0.3                      # Allows you to monitor network connectivity in Flutter.
  dartz: ^0.10.1                                 # A functional programming library for Dart.
  dio: ^5.4.3+1                                    # A powerful HTTP client for making network requests in Flutter.
  dio_cookie_manager: ^3.1.1                     # Cookie manager for Dio HTTP client in Flutter.
  get_it: ^7.7.0                                 # A service locator for Flutter.
  injectable: ^2.4.2                             # Dependency injection for Flutter and Dart.
  flutter_screenutil: ^5.9.3                     # Adapt your Flutter app to different screen sizes.
  flutter_native_splash: ^2.4.0                  # Generate native splash screens for Flutter apps.
  flutter_bloc: ^8.1.6                           # Implements the BLoC pattern for state management in Flutter.
  freezed: ^2.5.2                                # Code generation for immutable classes in Dart/Flutter.
  freezed_annotation: ^2.4.1                     # Annotations for the Freezed library.
  fluttertoast: ^8.2.6                           # Show toast messages in your Flutter app.
  json_annotation: ^4.9.0                        # Code generation for JSON serialization/deserialization.
  equatable: ^2.0.5                              # Simplify equality comparisons in Dart/Flutter.
  shared_preferences: ^2.2.3                     # Persistent key-value storage for Flutter.
  hydrated_bloc: ^9.1.5                          # Flutter BLoC state persistence with HydratedBloc.
  pretty_dio_logger: ^1.3.1                      # Pretty logs for the Dio HTTP client in Flutter.

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^8.0.0               # A code generator for AutoRoute, a Flutter routing library.
  build_runner: ^2.4.11                       # A build system for generating Dart code in your Flutter project.
  flutter_launcher_icons: ^0.13.1            # A tool to generate launcher icons for your Flutter app.
  flutter_lints: ^4.0.0                      # A set of lint rules for Dart and Flutter projects.
  flutter_secure_storage: ^9.2.2             # A Flutter plugin for securely storing sensitive data.
  injectable_generator: ^2.6.1               # A code generator for the Injectable dependency injection library in Flutter.
  json_serializable: ^6.7.1                  # A code generation library for JSON serialization and deserialization in Dart/Flutter.
  pubspec_dependency_sorter: ^1.0.4          # A utility for sorting dependencies in your Flutter `pubspec.yaml` file.
  retrofit_generator: ^8.1.0                # A code generator for Retrofit, a type-safe HTTP client for Dart/Flutter.
  intl: ^0.19.0                                  # Internationalization and localization for Flutter.
  path_provider: ^2.1.3                          # Get filesystem paths in Flutter.


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lang/

flutter_icons:
  android: launcher_icon
  image_path: assets/icons/launcher_icon.png
  image_path_ios: assets/icons/launcher_icon.png
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: '#FFFFFF'
  image: assets/icons/launcher_icon.png
  android_12:
    color: '#FFFFFF'
  fullscreen: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
